version: '2'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dockercompose
    ports:
      - "5342:5432"
    networks:
      - cuba-network

  web:
    build: .
    environment:
      - CUBA_DATASOURCE_JDBCURL=jdbc:postgresql://postgres/dockercompose
      - CUBA_DATASOURCE_USERNAME=postgres
      - CUBA_DATASOURCE_PASSWORD=postgres123
    ports:
      - "8080:8080"
    networks:
      - cuba-network

networks:
  cuba-network: